name: Secretlint
on: [push, pull_request]
permissions:
  contents: read
jobs:
  secretlint:
    name: "Secretlint"
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        node_version: 16
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup Node ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node_version: ${{ matrix.node_version }}
      - name: Install
        run: npm install
      - name: Lint with Secretlint
        run: npx secretlint "**/*"
